### ISSUE TITLE
Unable to setup redis standalone bukkit

### ISSUE THREAD

**Issue by Gx678X** [bridgelol/votifier#6]
My Bukkit config looks like this:

  redis:
    uri: "redis://:REDISPASSWORD@DEDICATEDSERVERIPWITHREDISANDVOTIFIERSTANDALONE:6739/0"

I already tested if i can connect to redis and OK

[23:03:40 ERROR]: [Votifier] NuVotifier could not set up Redis for vote forwarding!
redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
        at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:89) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at redis.clients.jedis.Connection.connect(Connection.java:194) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:392) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at redis.clients.jedis.Connection.<init>(Connection.java:56) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at redis.clients.jedis.Jedis.<init>(Jedis.java:155) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at redis.clients.jedis.Jedis.<init>(Jedis.java:59) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at com.vexsoftware.votifier.forwarding.RedisForwardingSink.<init>(RedisForwardingSink.java:28) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at com.vexsoftware.votifier.NuVotifierBukkit.loadAndBind(NuVotifierBukkit.java:267) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at com.vexsoftware.votifier.NuVotifierBukkit.onEnable(NuVotifierBukkit.java:297) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-62]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-62]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-62]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-62]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: java.net.ConnectException: Connection refused
                at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
                at sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
                at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
                at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
                at java.net.Socket.connect(Socket.java:751) ~[?:?]
                at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:75) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:89) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at redis.clients.jedis.Connection.connect(Connection.java:194) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:392) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at redis.clients.jedis.Connection.<init>(Connection.java:56) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at redis.clients.jedis.Jedis.<init>(Jedis.java:155) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at redis.clients.jedis.Jedis.<init>(Jedis.java:59) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at com.vexsoftware.votifier.forwarding.RedisForwardingSink.<init>(RedisForwardingSink.java:28) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at com.vexsoftware.votifier.NuVotifierBukkit.loadAndBind(NuVotifierBukkit.java:267) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at com.vexsoftware.votifier.NuVotifierBukkit.onEnable(NuVotifierBukkit.java:297) ~[nuvotifier-bukkit-3.0.0-SNAPSHOT-dist.jar:?]
                at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
                at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-62]
                at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-62]
                at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
                at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-62]
                at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-62]
                at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-62]
                at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-62]
                at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-62]
                at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-62]
                at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-62]
                at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by bridgelol** [comment]
Does the standalone instance connect fine? Seems like a configuration error.

**Comment by Gx678X** [comment]
> Does the standalone instance connect fine? Seems like a configuration error.
Yeah standalone works fine, no errors, but the bukkit version is the one which is unable to connect

**Comment by bridgelol** [comment]
> > Does the standalone instance connect fine? Seems like a configuration error.
> > Yeah standalone works fine, no errors, but the bukkit version is the one which is unable to connect

Try this: https://github.com/bridgelol/votifier/releases/tag/secret-key

**Comment by Gx678X** [comment]
Hello thanks for the update, I will try it soon.

**Comment by Gx678X** [comment]
Works fine, but there's an issue, if players votes and its offline they dont get the reward (i already toggled true offline option)

**Comment by bridgelol** [comment]
> Works fine, but there's an issue, if players votes and its offline they dont get the reward (i already toggled true offline option)

Added in latest version.
